var hierarchy =
[
    [ "BoundsItem", "structBoundsItem.html", null ],
    [ "BuildSettings", "structBuildSettings.html", null ],
    [ "BVItem", "structBVItem.html", null ],
    [ "ConvexVolume", "structConvexVolume.html", null ],
    [ "CrowdToolParams", "structCrowdToolParams.html", null ],
    [ "cmdline::default_reader< T >", "structcmdline_1_1default__reader.html", null ],
    [ "DirtyEntry", "structDirtyEntry.html", null ],
    [ "dtBVNode", "structdtBVNode.html", null ],
    [ "dtCompressedTile", "structdtCompressedTile.html", null ],
    [ "dtCrowd", "classdtCrowd.html", null ],
    [ "dtCrowdAgent", "structdtCrowdAgent.html", null ],
    [ "dtCrowdAgentAnimation", "structdtCrowdAgentAnimation.html", null ],
    [ "dtCrowdAgentDebugInfo", "structdtCrowdAgentDebugInfo.html", null ],
    [ "dtCrowdAgentParams", "structdtCrowdAgentParams.html", null ],
    [ "dtCrowdNeighbour", "structdtCrowdNeighbour.html", null ],
    [ "dtFixedArray< T >", "classdtFixedArray.html", null ],
    [ "dtLayerMonotoneRegion", "structdtLayerMonotoneRegion.html", null ],
    [ "dtLayerSweepSpan", "structdtLayerSweepSpan.html", null ],
    [ "dtLink", "structdtLink.html", null ],
    [ "dtLocalBoundary", "classdtLocalBoundary.html", null ],
    [ "dtMeshHeader", "structdtMeshHeader.html", null ],
    [ "dtMeshTile", "structdtMeshTile.html", null ],
    [ "dtNavMesh", "classdtNavMesh.html", null ],
    [ "dtNavMeshCreateParams", "structdtNavMeshCreateParams.html", null ],
    [ "dtNavMeshParams", "structdtNavMeshParams.html", null ],
    [ "dtNavMeshQuery", "classdtNavMeshQuery.html", null ],
    [ "dtNode", "structdtNode.html", null ],
    [ "dtNodePool", "classdtNodePool.html", null ],
    [ "dtNodeQueue", "classdtNodeQueue.html", null ],
    [ "dtObstacleAvoidanceDebugData", "classdtObstacleAvoidanceDebugData.html", null ],
    [ "dtObstacleAvoidanceParams", "structdtObstacleAvoidanceParams.html", null ],
    [ "dtObstacleAvoidanceQuery", "classdtObstacleAvoidanceQuery.html", null ],
    [ "dtObstacleBox", "structdtObstacleBox.html", null ],
    [ "dtObstacleCircle", "structdtObstacleCircle.html", null ],
    [ "dtObstacleCylinder", "structdtObstacleCylinder.html", null ],
    [ "dtObstacleOrientedBox", "structdtObstacleOrientedBox.html", null ],
    [ "dtObstacleSegment", "structdtObstacleSegment.html", null ],
    [ "dtOffMeshConnection", "structdtOffMeshConnection.html", null ],
    [ "dtPathCorridor", "classdtPathCorridor.html", null ],
    [ "dtPathQueue", "classdtPathQueue.html", null ],
    [ "dtPoly", "structdtPoly.html", null ],
    [ "dtPolyDetail", "structdtPolyDetail.html", null ],
    [ "dtPolyQuery", "classdtPolyQuery.html", [
      [ "dtCollectPolysQuery", "classdtCollectPolysQuery.html", null ],
      [ "dtFindNearestPolyQuery", "classdtFindNearestPolyQuery.html", null ]
    ] ],
    [ "dtPolyState", "structdtPolyState.html", null ],
    [ "dtProximityGrid", "classdtProximityGrid.html", null ],
    [ "dtQueryFilter", "classdtQueryFilter.html", null ],
    [ "dtRaycastHit", "structdtRaycastHit.html", null ],
    [ "dtSegInterval", "structdtSegInterval.html", null ],
    [ "dtTempContour", "structdtTempContour.html", null ],
    [ "dtTileCache", "classdtTileCache.html", null ],
    [ "dtTileCacheAlloc", "structdtTileCacheAlloc.html", [
      [ "LinearAllocator", "structLinearAllocator.html", null ],
      [ "LinearAllocator", "structLinearAllocator.html", null ]
    ] ],
    [ "dtTileCacheCompressor", "structdtTileCacheCompressor.html", [
      [ "FastLZCompressor", "structFastLZCompressor.html", null ],
      [ "FastLZCompressor", "structFastLZCompressor.html", null ]
    ] ],
    [ "dtTileCacheContour", "structdtTileCacheContour.html", null ],
    [ "dtTileCacheContourSet", "structdtTileCacheContourSet.html", null ],
    [ "dtTileCacheLayer", "structdtTileCacheLayer.html", null ],
    [ "dtTileCacheLayerHeader", "structdtTileCacheLayerHeader.html", null ],
    [ "dtTileCacheMeshProcess", "structdtTileCacheMeshProcess.html", [
      [ "MeshProcess", "structMeshProcess.html", null ],
      [ "MeshProcess", "structMeshProcess.html", null ]
    ] ],
    [ "dtTileCacheObstacle", "structdtTileCacheObstacle.html", null ],
    [ "dtTileCacheParams", "structdtTileCacheParams.html", null ],
    [ "dtTileCachePolyMesh", "structdtTileCachePolyMesh.html", null ],
    [ "dtTileState", "structdtTileState.html", null ],
    [ "duDebugDraw", "structduDebugDraw.html", [
      [ "DebugDrawGL", "classDebugDrawGL.html", [
        [ "SampleDebugDraw", "classSampleDebugDraw.html", null ],
        [ "SampleDebugDraw", "classSampleDebugDraw.html", null ]
      ] ],
      [ "DebugDrawGL", "classDebugDrawGL.html", null ],
      [ "duDisplayList", "classduDisplayList.html", null ]
    ] ],
    [ "duFileIO", "structduFileIO.html", [
      [ "FileIO", "classFileIO.html", null ],
      [ "FileIO", "classFileIO.html", null ]
    ] ],
    [ "std::exception", null, [
      [ "cmdline::cmdline_error", "classcmdline_1_1cmdline__error.html", null ]
    ] ],
    [ "GLCheckerTexture", "classGLCheckerTexture.html", null ],
    [ "GraphParams", "structGraphParams.html", null ],
    [ "GuiState", "structGuiState.html", null ],
    [ "imguiGfxCmd", "structimguiGfxCmd.html", null ],
    [ "imguiGfxLine", "structimguiGfxLine.html", null ],
    [ "imguiGfxRect", "structimguiGfxRect.html", null ],
    [ "imguiGfxText", "structimguiGfxText.html", null ],
    [ "InputGeom", "classInputGeom.html", null ],
    [ "cmdline::detail::is_same< T1, T2 >", "structcmdline_1_1detail_1_1is__same.html", null ],
    [ "cmdline::detail::is_same< T, T >", "structcmdline_1_1detail_1_1is__same_3_01T_00_01T_01_4.html", null ],
    [ "cmdline::detail::lexical_cast_t< Target, Source, Same >", "classcmdline_1_1detail_1_1lexical__cast__t.html", null ],
    [ "cmdline::detail::lexical_cast_t< std::string, Source, false >", "classcmdline_1_1detail_1_1lexical__cast__t_3_01std_1_1string_00_01Source_00_01false_01_4.html", null ],
    [ "cmdline::detail::lexical_cast_t< Target, Source, true >", "classcmdline_1_1detail_1_1lexical__cast__t_3_01Target_00_01Source_00_01true_01_4.html", null ],
    [ "cmdline::detail::lexical_cast_t< Target, std::string, false >", "classcmdline_1_1detail_1_1lexical__cast__t_3_01Target_00_01std_1_1string_00_01false_01_4.html", null ],
    [ "NavMesh", "classNavMesh.html", null ],
    [ "NavMeshContex", "classNavMeshContex.html", null ],
    [ "NavmeshFlags", "classNavmeshFlags.html", null ],
    [ "NavMeshSetHeader", "structNavMeshSetHeader.html", null ],
    [ "NavMeshTileBuildContext", "structNavMeshTileBuildContext.html", null ],
    [ "NavMeshTileHeader", "structNavMeshTileHeader.html", null ],
    [ "cmdline::oneof_reader< T >", "structcmdline_1_1oneof__reader.html", null ],
    [ "cmdline::parser", "classcmdline_1_1parser.html", null ],
    [ "cmdline::range_reader< T >", "structcmdline_1_1range__reader.html", null ],
    [ "RasterizationContext", "structRasterizationContext.html", null ],
    [ "rcChunkyTriMesh", "structrcChunkyTriMesh.html", null ],
    [ "rcChunkyTriMeshNode", "structrcChunkyTriMeshNode.html", null ],
    [ "rcCompactCell", "structrcCompactCell.html", null ],
    [ "rcCompactHeightfield", "structrcCompactHeightfield.html", null ],
    [ "rcCompactSpan", "structrcCompactSpan.html", null ],
    [ "rcConfig", "structrcConfig.html", null ],
    [ "rcContext", "classrcContext.html", [
      [ "BuildContext", "classBuildContext.html", null ],
      [ "BuildContext", "classBuildContext.html", null ]
    ] ],
    [ "rcContour", "structrcContour.html", null ],
    [ "rcContourHole", "structrcContourHole.html", null ],
    [ "rcContourRegion", "structrcContourRegion.html", null ],
    [ "rcContourSet", "structrcContourSet.html", null ],
    [ "rcEdge", "structrcEdge.html", null ],
    [ "rcHeightfield", "structrcHeightfield.html", null ],
    [ "rcHeightfieldLayer", "structrcHeightfieldLayer.html", null ],
    [ "rcHeightfieldLayerSet", "structrcHeightfieldLayerSet.html", null ],
    [ "rcHeightPatch", "structrcHeightPatch.html", null ],
    [ "rcLayerRegion", "structrcLayerRegion.html", null ],
    [ "rcLayerSweepSpan", "structrcLayerSweepSpan.html", null ],
    [ "rcMeshLoaderObj", "classrcMeshLoaderObj.html", null ],
    [ "rcNewTag", "structrcNewTag.html", null ],
    [ "rcPolyMesh", "structrcPolyMesh.html", null ],
    [ "rcPolyMeshDetail", "structrcPolyMeshDetail.html", null ],
    [ "rcPotentialDiagonal", "structrcPotentialDiagonal.html", null ],
    [ "rcRegion", "structrcRegion.html", null ],
    [ "rcScopedDelete< T >", "classrcScopedDelete.html", null ],
    [ "rcScopedTimer", "classrcScopedTimer.html", null ],
    [ "rcSpan", "structrcSpan.html", null ],
    [ "rcSpanPool", "structrcSpanPool.html", null ],
    [ "rcSweepSpan", "structrcSweepSpan.html", null ],
    [ "rcVectorBase< T, H >", "classrcVectorBase.html", [
      [ "rcTempVector< int >", "classrcTempVector.html", null ]
    ] ],
    [ "rcVectorBase< int, RC_ALLOC_TEMP >", "classrcVectorBase.html", null ],
    [ "rcVectorBase< T, RC_ALLOC_PERM >", "classrcVectorBase.html", [
      [ "rcPermVector< T >", "classrcPermVector.html", null ]
    ] ],
    [ "rcVectorBase< T, RC_ALLOC_TEMP >", "classrcVectorBase.html", [
      [ "rcTempVector< T >", "classrcTempVector.html", null ]
    ] ],
    [ "Sample", "classSample.html", [
      [ "Sample_Debug", "classSample__Debug.html", null ],
      [ "Sample_Debug", "classSample__Debug.html", null ],
      [ "Sample_SoloMesh", "classSample__SoloMesh.html", null ],
      [ "Sample_SoloMesh", "classSample__SoloMesh.html", null ],
      [ "Sample_TempObstacles", "classSample__TempObstacles.html", null ],
      [ "Sample_TempObstacles", "classSample__TempObstacles.html", null ],
      [ "Sample_TileMesh", "classSample__TileMesh.html", null ],
      [ "Sample_TileMesh", "classSample__TileMesh.html", null ]
    ] ],
    [ "SampleItem", "structSampleItem.html", null ],
    [ "SampleTool", "structSampleTool.html", [
      [ "ConvexVolumeTool", "classConvexVolumeTool.html", null ],
      [ "ConvexVolumeTool", "classConvexVolumeTool.html", null ],
      [ "CrowdTool", "classCrowdTool.html", null ],
      [ "CrowdTool", "classCrowdTool.html", null ],
      [ "NavMeshPruneTool", "classNavMeshPruneTool.html", null ],
      [ "NavMeshPruneTool", "classNavMeshPruneTool.html", null ],
      [ "NavMeshTesterTool", "classNavMeshTesterTool.html", null ],
      [ "NavMeshTileTool", "classNavMeshTileTool.html", null ],
      [ "NavMeshTileTool", "classNavMeshTileTool.html", null ],
      [ "OffMeshConnectionTool", "classOffMeshConnectionTool.html", null ],
      [ "OffMeshConnectionTool", "classOffMeshConnectionTool.html", null ],
      [ "TempObstacleCreateTool", "classTempObstacleCreateTool.html", null ],
      [ "TempObstacleCreateTool", "classTempObstacleCreateTool.html", null ],
      [ "TempObstacleHilightTool", "classTempObstacleHilightTool.html", null ],
      [ "TempObstacleHilightTool", "classTempObstacleHilightTool.html", null ]
    ] ],
    [ "SampleToolState", "structSampleToolState.html", [
      [ "CrowdToolState", "classCrowdToolState.html", null ],
      [ "CrowdToolState", "classCrowdToolState.html", null ]
    ] ],
    [ "SDL_AssertData", "structSDL__AssertData.html", null ],
    [ "SDL_atomic_t", "structSDL__atomic__t.html", null ],
    [ "SDL_AudioCVT", "structSDL__AudioCVT.html", null ],
    [ "SDL_AudioDeviceEvent", "structSDL__AudioDeviceEvent.html", null ],
    [ "SDL_AudioSpec", "structSDL__AudioSpec.html", null ],
    [ "SDL_Color", "structSDL__Color.html", null ],
    [ "SDL_CommonEvent", "structSDL__CommonEvent.html", null ],
    [ "SDL_ControllerAxisEvent", "structSDL__ControllerAxisEvent.html", null ],
    [ "SDL_ControllerButtonEvent", "structSDL__ControllerButtonEvent.html", null ],
    [ "SDL_ControllerDeviceEvent", "structSDL__ControllerDeviceEvent.html", null ],
    [ "SDL_ControllerSensorEvent", "structSDL__ControllerSensorEvent.html", null ],
    [ "SDL_ControllerTouchpadEvent", "structSDL__ControllerTouchpadEvent.html", null ],
    [ "SDL_DisplayEvent", "structSDL__DisplayEvent.html", null ],
    [ "SDL_DisplayMode", "structSDL__DisplayMode.html", null ],
    [ "SDL_DollarGestureEvent", "structSDL__DollarGestureEvent.html", null ],
    [ "SDL_DropEvent", "structSDL__DropEvent.html", null ],
    [ "SDL_Event", "unionSDL__Event.html", null ],
    [ "SDL_Finger", "structSDL__Finger.html", null ],
    [ "SDL_FPoint", "structSDL__FPoint.html", null ],
    [ "SDL_FRect", "structSDL__FRect.html", null ],
    [ "SDL_GameControllerButtonBind", "structSDL__GameControllerButtonBind.html", null ],
    [ "SDL_GUID", "structSDL__GUID.html", null ],
    [ "SDL_HapticCondition", "structSDL__HapticCondition.html", null ],
    [ "SDL_HapticConstant", "structSDL__HapticConstant.html", null ],
    [ "SDL_HapticCustom", "structSDL__HapticCustom.html", null ],
    [ "SDL_HapticDirection", "structSDL__HapticDirection.html", null ],
    [ "SDL_HapticEffect", "unionSDL__HapticEffect.html", null ],
    [ "SDL_HapticLeftRight", "structSDL__HapticLeftRight.html", null ],
    [ "SDL_HapticPeriodic", "structSDL__HapticPeriodic.html", null ],
    [ "SDL_HapticRamp", "structSDL__HapticRamp.html", null ],
    [ "SDL_hid_device_info", "structSDL__hid__device__info.html", null ],
    [ "SDL_JoyAxisEvent", "structSDL__JoyAxisEvent.html", null ],
    [ "SDL_JoyBallEvent", "structSDL__JoyBallEvent.html", null ],
    [ "SDL_JoyBatteryEvent", "structSDL__JoyBatteryEvent.html", null ],
    [ "SDL_JoyButtonEvent", "structSDL__JoyButtonEvent.html", null ],
    [ "SDL_JoyDeviceEvent", "structSDL__JoyDeviceEvent.html", null ],
    [ "SDL_JoyHatEvent", "structSDL__JoyHatEvent.html", null ],
    [ "SDL_KeyboardEvent", "structSDL__KeyboardEvent.html", null ],
    [ "SDL_Keysym", "structSDL__Keysym.html", null ],
    [ "SDL_Locale", "structSDL__Locale.html", null ],
    [ "SDL_MessageBoxButtonData", "structSDL__MessageBoxButtonData.html", null ],
    [ "SDL_MessageBoxColor", "structSDL__MessageBoxColor.html", null ],
    [ "SDL_MessageBoxColorScheme", "structSDL__MessageBoxColorScheme.html", null ],
    [ "SDL_MessageBoxData", "structSDL__MessageBoxData.html", null ],
    [ "SDL_MouseButtonEvent", "structSDL__MouseButtonEvent.html", null ],
    [ "SDL_MouseMotionEvent", "structSDL__MouseMotionEvent.html", null ],
    [ "SDL_MouseWheelEvent", "structSDL__MouseWheelEvent.html", null ],
    [ "SDL_MultiGestureEvent", "structSDL__MultiGestureEvent.html", null ],
    [ "SDL_Palette", "structSDL__Palette.html", null ],
    [ "SDL_PixelFormat", "structSDL__PixelFormat.html", null ],
    [ "SDL_Point", "structSDL__Point.html", null ],
    [ "SDL_QuitEvent", "structSDL__QuitEvent.html", null ],
    [ "SDL_Rect", "structSDL__Rect.html", null ],
    [ "SDL_RendererInfo", "structSDL__RendererInfo.html", null ],
    [ "SDL_RWops", "structSDL__RWops.html", null ],
    [ "SDL_SensorEvent", "structSDL__SensorEvent.html", null ],
    [ "SDL_Surface", "structSDL__Surface.html", null ],
    [ "SDL_SysWMEvent", "structSDL__SysWMEvent.html", null ],
    [ "SDL_SysWMinfo", "structSDL__SysWMinfo.html", null ],
    [ "SDL_SysWMmsg", "structSDL__SysWMmsg.html", null ],
    [ "SDL_TextEditingEvent", "structSDL__TextEditingEvent.html", null ],
    [ "SDL_TextEditingExtEvent", "structSDL__TextEditingExtEvent.html", null ],
    [ "SDL_TextInputEvent", "structSDL__TextInputEvent.html", null ],
    [ "SDL_TouchFingerEvent", "structSDL__TouchFingerEvent.html", null ],
    [ "SDL_UserEvent", "structSDL__UserEvent.html", null ],
    [ "SDL_version", "structSDL__version.html", null ],
    [ "SDL_Vertex", "structSDL__Vertex.html", null ],
    [ "SDL_VirtualJoystickDesc", "structSDL__VirtualJoystickDesc.html", null ],
    [ "SDL_WindowEvent", "structSDL__WindowEvent.html", null ],
    [ "SDL_WindowShapeMode", "structSDL__WindowShapeMode.html", null ],
    [ "SDL_WindowShapeParams", "unionSDL__WindowShapeParams.html", null ],
    [ "SDLTest_CommonState", "structSDLTest__CommonState.html", null ],
    [ "SDLTest_Crc32Context", "structSDLTest__Crc32Context.html", null ],
    [ "SDLTest_Md5Context", "structSDLTest__Md5Context.html", null ],
    [ "SDLTest_RandomContext", "structSDLTest__RandomContext.html", null ],
    [ "SDLTest_SurfaceImage_s", "structSDLTest__SurfaceImage__s.html", null ],
    [ "SDLTest_TestCaseReference", "structSDLTest__TestCaseReference.html", null ],
    [ "SDLTest_TestSuiteReference", "structSDLTest__TestSuiteReference.html", null ],
    [ "SDLTest_TextWindow", "structSDLTest__TextWindow.html", null ],
    [ "stbtt__bitmap", "structstbtt____bitmap.html", null ],
    [ "stbtt_aligned_quad", "structstbtt__aligned__quad.html", null ],
    [ "stbtt_bakedchar", "structstbtt__bakedchar.html", null ],
    [ "stbtt_fontinfo", "structstbtt__fontinfo.html", null ],
    [ "stbtt_pack_context", "structstbtt__pack__context.html", null ],
    [ "stbtt_pack_range", "structstbtt__pack__range.html", null ],
    [ "stbtt_packedchar", "structstbtt__packedchar.html", null ],
    [ "stbtt_vertex", "structstbtt__vertex.html", null ],
    [ "TestCase", "classTestCase.html", null ],
    [ "TileCacheData", "structTileCacheData.html", null ],
    [ "TileCacheSetHeader", "structTileCacheSetHeader.html", null ],
    [ "TileCacheTileHeader", "structTileCacheTileHeader.html", null ],
    [ "ValueHistory", "classValueHistory.html", null ]
];