/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_gamioo_nav_NavEngine */

#ifndef _Included_io_gamioo_nav_NavEngine
#define _Included_io_gamioo_nav_NavEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_gamioo_nav_NavEngine
 * Method:    load
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_io_gamioo_nav_NavEngine_load
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     io_gamioo_nav_NavEngine
 * Method:    find
 * Signature: (IFFFFFF)[F
 */
JNIEXPORT jfloatArray JNICALL Java_io_gamioo_nav_NavEngine_find
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     io_gamioo_nav_NavEngine
 * Method:    findNearest
 * Signature: (IFFF)[F
 */
JNIEXPORT jfloatArray JNICALL Java_io_gamioo_nav_NavEngine_findNearest
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat);

/*
 * Class:     io_gamioo_nav_NavEngine
 * Method:    raycast
 * Signature: (IFFFFFF)[F
 */
JNIEXPORT jfloatArray JNICALL Java_io_gamioo_nav_NavEngine_raycast
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     io_gamioo_nav_NavEngine
 * Method:    release
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_gamioo_nav_NavEngine_release
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_gamioo_nav_NavEngine
 * Method:    releaseAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_gamioo_nav_NavEngine_releaseAll
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
