/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_gamioo_path_Nav3D */

#ifndef _Included_io_gamioo_path_Nav3D
#define _Included_io_gamioo_path_Nav3D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_gamioo_path_Nav3D
 * Method:    load
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_io_gamioo_path_Nav3D_load
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     io_gamioo_path_Nav3D
 * Method:    find
 * Signature: (IFFFFFF)[F
 */
JNIEXPORT jfloatArray JNICALL Java_io_gamioo_path_Nav3D_find
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     io_gamioo_path_Nav3D
 * Method:    findNearest
 * Signature: (IFFF)[F
 */
JNIEXPORT jfloatArray JNICALL Java_io_gamioo_path_Nav3D_findNearest
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat);

/*
 * Class:     io_gamioo_path_Nav3D
 * Method:    raycast
 * Signature: (IFFFFFF)[F
 */
JNIEXPORT jfloatArray JNICALL Java_io_gamioo_path_Nav3D_raycast
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     io_gamioo_path_Nav3D
 * Method:    release
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_gamioo_path_Nav3D_release
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_gamioo_path_Nav3D
 * Method:    releaseAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_gamioo_path_Nav3D_releaseAll
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
